spring:
  application:
    name: auction-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: open-api
#          uri: http://localhost:8080
##          uri: lb://auction-service
#          predicates:
#            - Path=/api/v1/auth/**, /error, /style.css, /api/v2/auctions/search, /api/v2/auctions/elasticsearch, /actuator/health, /health, /actuator/prometheus

        - id: points-service
#          uri: http://localhost:8080/api/
          uri: lb://points-service
          predicates:
            - Path=api/v1/points/**, /api/v2/points/**, /payment/**
          filters:
#            - AddRequestHeader=Authorization,Bearer {token}

        - id: auction-service
#          uri: http://localhost:8080
          uri: lb://auction-service
          predicates:
            - Path=/**

      httpclient:
        max-header-size: 16384


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

  instance:
    prefer-ip-address: true
    ip-address: ${EC2_PRIVATE_IP}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.security: DEBUG
