spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: swagger-ui
          uri: http://localhost:8080  # 게이트웨이 자체가 요청을 처리
          predicates:
            - Path=/swagger-ui.html
        - id: points-service
          uri: lb://points-service
          predicates:
            - Path=/api/v1/points/**, /api/v2/points/**, /payment/**, /points/**, /style.css
          filters:
            - RewritePath=/points/(?<segment>.*), /$\{segment}
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/auction/**, /**
          filters:
            - RewritePath=/auction/(?<segment>.*), /$\{segment}
      httpclient:
        max-header-size: 16384
        connect-timeout: 10000  # 10초
        response-timeout: 60000 # 60초

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

  instance:
    prefer-ip-address: true
    ip-address: ${EC2_PRIVATE_IP}

springdoc:
  swagger-ui:
    urls:
      - name: Auction Service
        url: http://${EC2_PRIVATE_IP}:8080/auction/v3/api-docs
      - name: Point Service
        url: http://${EC2_PRIVATE_IP}:8080/points/v3/api-docs

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http: DEBUG
