spring:
  application:
    name: auction-gateway

  cloud:
    gateway:
#      default-filters:
#        - name: JwtAuthenticationFilter
      routes:
        - id: open-api              # ?? ??
          uri: http://localhost:8080
#          uri: lb://auction-service
          predicates:
            - Path=/api/v1/auth/**, /error, /style.css, /api/v2/auctions/search, /api/v2/auctions/elasticsearch, /actuator/health, /health, /actuator/prometheus

        - id: points-service
#          uri: http://localhost:8080/api/   # ?? ? ???
          uri: lb://points-service         # Eureka?? ??? ?? (?? ????????? ???)
          predicates:
            - Path=api/v1/points/**, api/v2/points/**           # /points ??? ???? ?? points-service? ???
          filters:
            - JwtAuthenticationFilter

        - id: auction-service
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - JwtAuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret:
    key: ${JWT_SECRET_KEY}